### PR TITLE
JENKINS-28641 - Allow for configuration of a custom command shell when using docker

### PR DESCRIPTION
**Pull request by nickithewatt**
This PR addresses https://issues.jenkins-ci.org/browse/JENKINS-28641 which makes it possible to configure the use of a custom command shell when executing a docker based slave, which is helpful when trying to run a docker-in-docker / dind image.

This issue was also raised in the google group here:
https://groups.google.com/forum/#!topic/jenkins-mesos/JgFCmqOO7Fg

### CODE REVIEW

**Comment by nikore** [comment]
Thanks I ended up having to make my own version of the plug in with this in there, but it works great.

**Comment by maselvaraj** [comment]
@nickithewatt Thanks for the PR! Can you please merge the latest changes from master, address the comments and squash your commits into one? We shall cut a release soon.

**Comment by bacoboy** [comment]
This keeps getting passed over for merge.  Can we get this (#112) pulled in along with #121 and #131 so my team can stop using a fork?

Happy to help with conflicts if need be...

**Comment by nickithewatt** [comment]
I am back from holiday now so will rebase and squash commits for new merge today

**Comment by maselvaraj** [comment]
@nickithewatt  Thank you!

**Comment by nickithewatt** [comment]
Sorry bit of a git push issue, new PR under https://github.com/jenkinsci/mesos-plugin/pull/141

**Pull request closed without merging**
