### PR TITLE
Update Parent POM and fix dependencies to make it runnable in PCT

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Just hit some issues while running PCT for JEP-200.

@reviewbybees

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Jenkins-on-Jenkins has not created job for it due to whatever reason

**Comment by dwnusbaum** [comment]
> Jenkins-on-Jenkins has not created job for it due to whatever reason

Probably it will be fixed after this is merged and the [CI job](https://ci.jenkins.io/job/Plugins/job/mesos-plugin/) is re-indexed, right?

**Comment by oleg-nenashev** [comment]
Nope, there is a bug in Branch API
https://issues.jenkins-ci.org/browse/JENKINS-48890

**Comment by oleg-nenashev** [comment]
@reviewbybees done

**Pull request merged**
