### PR TITLE
introduced affinity in offer selection

### PR DESCRIPTION
**Pull request by sathiya-mit**

### CODE REVIEW

**Comment by sathiya-mit** [comment]
@maselvaraj @vinodkone Please review it and let me know your valuable comments.

**Comment by sathiya-mit** [comment]
Along with this pull request, I have provided a fix for https://github.com/jenkinsci/mesos-plugin/issues/204

**Comment by Vlatombe** [comment]
Do you mind providing your NPE fix in a separate pull request? This has nothing to do with the current PR.

**Comment by sathiya-mit** [comment]
sure will do...

**Comment by maselvaraj** [comment]
@Vlatombe this pull request bumps up the most recently used mesos slave in the offer list[if it is available]. If the job goes to the same slave once again, build time will be faster than going to a new slave. Thoughts ?

**Comment by Vlatombe** [comment]
I think the intent is ok, but why limit ourselves to the latest slave? I'd store a LRU of slave id instead rather than the hostname.

**Comment by sathiya-mit** [comment]
@Vlatombe Thanks for your comment. Just to make it simple. I did this way.
Do you want to store all the used slave ids in a LRU fashion, and juggle the entire offer list to most recently used order ?

**Comment by Vlatombe** [comment]
I would store the 10 latest slaves id (size configurable through a system property) and prioritize these.

**Comment by sathiya-mit** [comment]
@Vlatombe Thanks for your quick response. I will make the necessary change.

**Comment by sathiya-mit** [comment]
Implemented LRU as you suggested. Please let me know your thoughts.

**Comment by geoffroyjabouley** [comment]
Hello

can you please provide more details on how this is intended to speed up
builds?

Are you mounting on each jenkins slave a workspace volume local on each
mesos slave machine?

2016-03-05 16:34 GMT+01:00 Sathiya Narayanan <notifications@github.com>:

**Comment by sathiya-mit** [comment]
@geoffroyjabouley Take the case of maven job, if we provide a recent slave (where the job has already ran) we can prevent downloading the maven dependency jars/artifacts again. This will help us in improving the maven build time.

Nope, We don't mount workspace volume on each mesos slave machine.

**Comment by geoffroyjabouley** [comment]
Thanks
your use case seems to indicate that you execute your jobs in jenkins
slaves running directly on the mesos slave machine, without docker
containerizer. Am i right?

2016-03-06 18:45 GMT+01:00 Sathiya Narayanan <notifications@github.com>:

**Comment by sathiya-mit** [comment]
@geoffroyjabouley Yes, You are right.

**Comment by maselvaraj** [comment]
@geoffroyjabouley It makes sense only if Mesos plugin is configured with custom remoteFS root. That is the Jenkins slave provisioned  through Mesos plugin will use the same path for workspace in any mesos slave.

**Comment by sathiya-mit** [comment]
@Vlatombe thanks for reviewing and merging it :+1:

**Pull request merged**
