### PR TITLE
Introduce support for Mesos maintenance primitives

### PR DESCRIPTION
**Pull request by ederst**
This commit introduces the feature for the frameworks registered by Jenkins to ignore
offers having an unavailability (maintenance primitive) set.

The offers are only ignored when the current time is between the start and end time (start + duration)
of the unavailability.

Issue: https://github.com/jenkinsci/mesos-plugin/issues/216

### CODE REVIEW

**Comment by nnordrum** [comment]
did I miss an update from Mesos where they _are_ planning on supporting Maintenance Primitives in the .so? Last I checked, which was a while ago, they were only going to support Maintenance Primitives in the HTTP API.

**Comment by ederst** [comment]
IDK. I read the posts in https://github.com/jenkinsci/mesos-plugin/issues/216 too and saw that it is not supported. However, I debugged the code and when I schedule a maintenance on my 0.27.2 Mesos  cluster the offers for the specified host(s) in the schedule contain an `Unavailability` object when entering `resourceOffers()`.

**Comment by nnordrum** [comment]
Interesting--well it that's the case, I would likely prefer this over #242.

**Comment by ederst** [comment]
One thing I found out during testing: It is not sufficient to just provide "host". The primitives only work if I specify the "ip" of the slave, too.

**Comment by ederst** [comment]
So I've tried this with the code of the pull request as well, and it works just fine. What this means is, that the plugin will not schedule a task/Jenkins slave on a Mesos agent being scheduled for downtime.

However, I forgot that this version of the plugin keeps Jenkins slaves online for a given time (deletes them when reaching an idle timeout and in the mean time utilizes them). Which means that potentially this could lead to an awfully long maintenance, waiting for the Jenkins slaves to vanish and the Mesos agents to drain.

Therefore, to improve and prevent this, the code would be better with some kind of mechanism to suspend/remove the Jenkins slaves of a Mesos agent which is currently in "draining_mode".

**Comment by nnordrum** [comment]
Well, "drain mode" is optional, as Frameworks aren't _required_ to fully drain for a maintenance period.

I agree it would be nice if it also drained idle/unschedulable slaves, but as long as it doesn't schedule new things on them, I'd be fine with that, at least for now.

I might also add another parameter of "don't schedule on node _N_ minutes before maintenance is scheduled to start" with a default of like 15.

**Comment by ederst** [comment]
> I might also add another parameter of "don't schedule on node N minutes before maintenance is scheduled to start" with a default of like 15.

Yeah, I don't know if this is necessary. You could simply schedule the maintenance window accordingly, so I don't think it is worth the hassle.

Btw. this still works with Mesos 1.2.0.

**Comment by maselvaraj** [comment]
Thanks @ederst for the PR! LGTM. Can you please add unit tests to cover this ?

**Comment by maselvaraj** [comment]
Thanks @ederst for the PR and the unit tests !

**Pull request merged**
