### PR TITLE
Update Jenkins dependencies.

### PR DESCRIPTION
**Pull request by janisz**
When I run tests I encourage following error:
```
Tests in error:
InjectedTest.initializationError(InjectedTest)
  Run 1: InjectedTest.suite:15 » NoClassDefFound org/mortbay/component/LifeCycle
  Run 2: InjectedTest.suite:15 » NoClassDefFound org/mortbay/component/LifeCycle
  Run 3: InjectedTest.suite:15 » NoClassDefFound org/mortbay/component/LifeCycle
  Run 4: InjectedTest.suite:15 » NoClassDefFound org/mortbay/component/LifeCycle
  Run 5: InjectedTest.suite:15 » NoClassDefFound org/mortbay/component/LifeCycle
```
Updating Jenkins dependecies fixed issue.

### CODE REVIEW

**Comment by maselvaraj** [comment]
@janisz Thanks for the PR. But I don't see these failures when I run the build. What is the JDK/Maven you are building the plugin against ?

**Comment by janisz** [comment]
@maselvaraj Tested on

```shell
➜  ~ java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
➜  ~ mvn -version 
Apache Maven 3.0.4
Maven home: /usr/share/maven
Java version: 1.8.0_111, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-65-generic", arch: "amd64", family: "unix"
➜  ~ mvn3 -version
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T18:37:52+01:00)
Maven home: /usr/share/maven3
Java version: 1.8.0_111, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-65-generic", arch: "amd64", family: "unix"
```

**Comment by janisz** [comment]
It's passing on Travis https://travis-ci.org/janisz/mesos-plugin so it's probably issue with my setup.

**Comment by maselvaraj** [comment]
Thanks @janisz for confirming. Can you please close this PR ?

**Comment by janisz** [comment]
It's worth to merge. It updates dependencies with bug fixes and remove unnecessary properties in pom.

**Pull request closed without merging**
