### PR TITLE
[JENKINS-49117] - Stop serializing ReentrantLocks to the disk

### PR DESCRIPTION
**Pull request by oleg-nenashev**
It includes #309 for testing purposes and includes a hotfix for https://issues.jenkins-ci.org/browse/JENKINS-49117 to make the plugin compatible with Jenkins 2.102+

@reviewbybees @jglick

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@reviewbybees done

**Comment by oleg-nenashev** [comment]
@maselvaraj @Vlatombe @jenkinsci/mesos-plugin-developers would it be possible to review/release it? In the current state the plugin is not fully operational on Jenkins 2.102+

**Comment by Vlatombe** [comment]
lgtm but I no longer have use mesos environments regularly so no time to test it.

**Comment by oleg-nenashev** [comment]
@Vlatombe @maselvaraj Without this fix the plugin is not compatible with Jenkins 2.102+. Would it be possible to review/release the fix? Thanks in advance

**Comment by oleg-nenashev** [comment]
@Vlatombe let me know once it is released. I will update the documentation

**Comment by Vlatombe** [comment]
@oleg-nenashev Done (0.15.1).

**Comment by oleg-nenashev** [comment]
@Vlatombe thanks a lot!

**Pull request merged**
